version: "3.3"

services:
  topic:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    environment:
      - TELEGRAM_API_TOKEN
      - TELEGRAM_BOT_USERNAME
      - MONGO_HOST="mongodb_container"
    networks:
      topics-net:

  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    networks:
      topics-net:

volumes:
  mongodb_data_container:
networks:
  topics-net: